ticket_index:
    path:     /
    defaults: { _controller: "INAdminBundle:Ticket:index" }
    methods:  GET

ticket_show:
    path:     /{id}/show
    defaults: { _controller: "INAdminBundle:Ticket:show" }
    methods:  GET

ticket_new:
    path:     /new
    defaults: { _controller: "INAdminBundle:Ticket:new" }
    methods:  [GET, POST]

ticket_edit:
    path:     /{id}/edit
    defaults: { _controller: "INAdminBundle:Ticket:edit" }
    methods:  [GET, POST]

ticket_delete:
    path:     /{id}/delete
    defaults: { _controller: "INAdminBundle:Ticket:delete" }
    methods:  DELETE
